### ISSUE TITLE
Cache bug on Safari

### ISSUE THREAD

**Issue by finnless** [IonImpulse/MAKE#2]
## Bug Description

MAKE has a bug on Safari on all devices that causes all resources on make.hmc.edu to not load on every other page refresh. This behavior has existed for as long as I have used the site (1+ year). I believe this is a caching issue thus is difficult to troubleshoot. This appears to be an issue with the deployment configuration and not a problem with any of the actual code. This is how the site behaves:

https://user-images.githubusercontent.com/6785029/232973362-0e1c1c99-263e-4d48-a8ba-4b9bf3971f73.mov

## HTTP Header Analysis

Here are some comparisons of how the https://make.hmc.edu/img/home-icon.svg resource loads.

### Response from make.hmc.edu
```
:status: 200
Content-Encoding: gzip
ETag: "72a:62db2d84"
Access-Control-Allow-Origin: *
Content-Type: image/svg+xml
Vary: accept-encoding, Origin, Access-Control-Request-Method, Access-Control-Request-Headers
Date: Wed, 19 Apr 2023 05:20:01 GMT
```

This is the initial response header when the client first connects. I'm still not exactly sure whats going wrong here. This should prime the browser to cache the response and ask`"If-None-Match": "72a:62db2d84"` in the next request where it should receive a 304. As far as I can tell, all of this happens even though the content does not appear to be cached.

### Response from local VS Code live server
```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Content-Type: image/svg+xml
Connection: keep-alive
Last-Modified: Wed, 19 Apr 2023 03:48:58 GMT
Cache-Control: public, max-age=0
ETag: W/"72a-18797a13822"
Accept-Ranges: bytes
Date: Wed, 19 Apr 2023 04:14:17 GMT
Keep-Alive: timeout=5
Content-Length: 3327
Vary: Origin
```

Running the site locally using VS Code live server works perfectly and the site is being cached properly as well.

## Further Troubleshooting

What web server does MAKE run on? I can tell its running on Azure, but I don't know more than that.

**Comment by IonImpulse** [comment]
This is a tricky one that is probably due to the weird way I handle SSL handover from a non-secure context. The rust server binds to two ports and has some funky middleware to direct traffic. This will be fixed in V2 (being rewritten in python right now) as I'm switching to an Nginx reverse proxy setup, running on one unified port.

**Comment by finnless** [comment]
Got it. Nginx will probably do the trick.
